version: '3.9'

services:
  dotnet:
    build: 
      context: ./dotnet
      dockerfile: Dockerfile
    ports:
      - "12345:12345"
    volumes:
      - ../src/:/app/
      - ../data/dotnet:/app/USTS_Server/data
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    # depends_on:
    #   - mongodb

  mongodb:
    build:
      context: ./mongodb
      dockerfile: Dockerfile
    ports:
      - "27017:27017"
    # volumes:
    #   - ../data/db:/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}

  mongo-express:
    build:
      context: ./mongodb-express
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - ME_CONFIG_MONGODB_SERVER=mongodb
    # depends_on:
    #   - mongodb
