# Use the official MongoDB image as a base image
FROM mongo:5.0

# Set up the working directory
# WORKDIR /db

# Copy any necessary initialization scripts
#COPY ./init-scripts /docker-entrypoint-initdb.d
